spring.application.name=payment-service
server.port=8086

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog.xml
spring.data.mongodb.database=paymentservice
spring.data.mongodb.uri=${MONGODB_URI}

api-gateway.url=${API_GATEWAY_URL}
random-number-client.url=https://www.random.org

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI}
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.create-payment=CREATE_PAYMENT