spring.application.name=payment-service

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog.xml
spring.liquibase.default-schema=paymentservice

spring.jpa.database=postgresql
spring.jpa.show-sql=true
